"""Build the character-bigram language model used by the DGA detector.

Reads the bundled corpus of legitimate registrable labels and writes
``backend/app/detection/data/bigrams.json`` containing:

* smoothed log P(next_char | previous_char) for every character pair
* the calibration statistics (mean and standard deviation) of the per-character
  log-likelihood ratio measured **on the corpus itself**

The calibration statistics are what turn a raw likelihood into an interpretable
"how many standard deviations less English-like than a normal domain is this?"
figure. They are measured, not invented.

Run:  python backend/scripts/build_bigram_model.py
"""

import json
import math
import sys
from collections import defaultdict
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT))

CORPUS = PROJECT_ROOT / "backend" / "app" / "detection" / "data" / "legit_domains.txt"
OUTPUT = PROJECT_ROOT / "backend" / "app" / "detection" / "data" / "bigrams.json"

ALPHABET = "abcdefghijklmnopqrstuvwxyz0123456789-"
START = "^"
END = "$"
SMOOTHING = 0.1  # add-k smoothing so unseen transitions stay finite


def load_corpus():
    labels = []
    with open(CORPUS, "r", encoding="utf-8") as handle:
        for line in handle:
            if line.lstrip().startswith("#"):
                continue
            for token in line.split():
                token = token.strip().lower()
                if token and all(ch in ALPHABET for ch in token):
                    labels.append(token)
    return sorted(set(labels))


def train(labels):
    """Count bigram transitions over ``^label$``."""
    counts = defaultdict(lambda: defaultdict(float))
    for label in labels:
        padded = START + label + END
        for i in range(len(padded) - 1):
            counts[padded[i]][padded[i + 1]] += 1.0

    from_chars = [START] + list(ALPHABET)
    to_chars = list(ALPHABET) + [END]

    log_probs = {}
    for previous in from_chars:
        row = counts.get(previous, {})
        total = sum(row.get(c, 0.0) for c in to_chars) + SMOOTHING * len(to_chars)
        log_probs[previous] = {
            c: round(math.log((row.get(c, 0.0) + SMOOTHING) / total), 5)
            for c in to_chars
        }
    return log_probs


def score(label, log_probs, uniform_logp):
    """Mean per-character log-likelihood ratio: legitimate vs uniform-random."""
    padded = START + label + END
    total = 0.0
    steps = 0
    for i in range(len(padded) - 1):
        row = log_probs.get(padded[i])
        if row is None:
            continue
        total += row.get(padded[i + 1], uniform_logp)
        steps += 1
    if steps == 0:
        return 0.0
    return (total / steps) - uniform_logp


def main():
    labels = load_corpus()
    if len(labels) < 100:
        raise SystemExit("Corpus too small: {} labels".format(len(labels)))

    log_probs = train(labels)
    uniform_logp = math.log(1.0 / (len(ALPHABET) + 1))

    scores = [score(label, log_probs, uniform_logp) for label in labels]
    mean = sum(scores) / len(scores)
    variance = sum((s - mean) ** 2 for s in scores) / len(scores)
    std = math.sqrt(variance)

    model = {
        "_comment": (
            "Character-bigram language model over legitimate registrable labels. "
            "Generated by backend/scripts/build_bigram_model.py - do not edit by hand. "
            "calibration.mean/std are the measured distribution of the per-character "
            "log-likelihood ratio across the training corpus, used to express how far "
            "below normal a candidate label sits."
        ),
        "version": "bigram_v1",
        "alphabet": ALPHABET,
        "smoothing": SMOOTHING,
        "corpus_size": len(labels),
        "uniform_logp": round(uniform_logp, 5),
        "calibration": {
            "mean": round(mean, 5),
            "std": round(std, 5),
            "min": round(min(scores), 5),
            "max": round(max(scores), 5),
        },
        "log_probs": log_probs,
    }

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as handle:
        json.dump(model, handle, indent=1, sort_keys=True)

    print("corpus labels : {}".format(len(labels)))
    print("llr mean      : {:.4f}".format(mean))
    print("llr std       : {:.4f}".format(std))
    print("llr range     : {:.4f} .. {:.4f}".format(min(scores), max(scores)))
    print("written       : {} ({:.0f} KB)".format(OUTPUT, OUTPUT.stat().st_size / 1024))


if __name__ == "__main__":
    main()
